import { brandConfig } from "@/config/brand";
export const loginConfig = {
    features: {
        googleSignIn: false,
        rememberMe: true,
        forgotPassword: true,
        supportFootnote: false,
        previewFallback: true,
        previewRoleSwitch: true,
        logoWatermark: false,
        areaWatermark: true,
    },
    routes: {
        login: "/login",
        forgotPassword: "/forgot-password",
        afterSignIn: "/admin",
        privacy: "/privacy",
    },
    validation: {
        minPasswordLength: 8,
        emailPattern: /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/,
    },
    /**
     * Seed silhouette: a climb, a trough, then a long rise to a peak that tapers
     * off — the shape reads as a month of trading rather than as noise.
     */
    area: {
        color: "var(--brand-lime)",
        interactive: true,
        hoverOpacity: 0.9,
        readoutLabel: "Revenue",
        data: [
            430, 470, 545, 600, 640, 662, 655, 671, 648, 590,
            560, 505, 430, 388, 372, 366, 380, 396, 402, 438,
            470, 520, 596, 648, 690, 742, 796, 828, 809, 772,
            742, 706, 688,
        ],
        motion: {
            stepMs: 900,
            durationMs: 850,
            driftRatio: 0.16,
            fadeFrom: 0.09,
            fadeTo: 0.15,
            fadeDurationMs: 9600,
        },
    },
    brand: brandConfig,
    content: {
        eyebrow: "Agency operations",
        headlineLead: "Welcome back to your",
        headlineAccent: "sales pipeline",
        subhead: "Track dials, appointments and conversions across the whole team — one dashboard, one source of truth.",
        statusLabel: "All systems operational",
        cardKicker: "Secure access",
        title: "Log in",
        subtitle: "Use your email and password to access the platform.",
        googleLabel: "Continue with Google",
        dividerLabel: "or continue with email",
        emailLabel: "Email address",
        emailPlaceholder: "you@stallionadvertising.ma",
        passwordLabel: "Password",
        passwordPlaceholder: "At least 8 characters",
        capsLockWarning: "Caps Lock is on.",
        showPasswordLabel: "Show password",
        hidePasswordLabel: "Hide password",
        forgotLabel: "Forgot password?",
        rememberLabel: "Keep me signed in",
        submitLabel: "Log in",
        submitPendingLabel: "Verifying",
        previewChipLabel: "Preview build",
        previewChipTooltip: "Authentication is not connected yet. Nothing is checked and no session is created — this door opens for anyone.",
        previewSubmitLabel: "Continue to console",
        previewHint: "No credentials needed while auth is disconnected.",
        previewRoleLabel: "Continue as",
        previewRoleHint: "Admin runs the agency, Sales works the pipeline, Dev delivers the work, Client sees their project.",
        previewRoleGroupLabel: "Choose which side of the product to open",
        previewRoles: [
            { role: "admin", label: "Admin", submitLabel: "Continue to console" },
            { role: "sales", label: "Sales", submitLabel: "Continue to my pipeline" },
            { role: "dev", label: "Dev", submitLabel: "Continue to workspace" },
            { role: "client", label: "Client", submitLabel: "Continue to portal" },
        ],
        supportFootnote: "No account yet?",
        supportLinkLabel: "Ask your administrator",
        legal: "Stallion Advertising",
        privacyLabel: "Privacy policy",
        errors: {
            emailRequired: "Enter your email address.",
            emailInvalid: "That does not look like a valid email address.",
            passwordRequired: "Enter your password.",
            passwordTooShort: "Password must be at least 8 characters.",
            unexpected: "Something went wrong. Please try again.",
        },
    },
};
